#!/usr/bin/env bash

az aks get-credentials --resource-group elastic-aks --name elastic-aks --overwrite-existing

kubectl apply -Rf k8s/storageclass/
kubectl create namespace elastic
kubectl apply -Rf k8s/specs/